Repository AY2223S2-CS2103T-W10-4/tp, pull requests merged in 2023-03, with the labels that each got.

#40 Update UG add command
  docs/UserGuide.md
Labels: priority.High, type.Chore

#41 Change Application Icon and name
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/tms.png
  src/main/resources/images/tms2.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, type.Chore

#45 Display subject and schedule; Modify UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story, priority.High

#46 Edit config.yml to new application
  docs/_config.yml
Labels: priority.Medium, type.Chore

#48 Add startTime and endTime fields to addComand
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/TuteeManagingSystem.java
  src/main/java/seedu/address/model/tutee/EndTime.java
  src/main/java/seedu/address/model/tutee/StartTime.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonTuteeManagingSystemStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/SerializableTestClass.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#49 Tests v1.2
  bin/main/images/tms.png
  bin/main/images/tms2.png
  bin/main/seedu/address/logic/commands/RemarkCommand.class
  bin/main/seedu/address/logic/parser/RemarkCommandParser.class
  bin/main/seedu/address/model/ReadOnlyTuteeManagingSystem.class
  bin/main/seedu/address/model/TuteeManagingSystem.class
  bin/main/seedu/address/model/tutee/Address.class
  bin/main/seedu/address/model/tutee/Email.class
  bin/main/seedu/address/model/tutee/Name.class
  bin/main/seedu/address/model/tutee/NameContainsKeywordsPredicate.class
  bin/main/seedu/address/model/tutee/Phone.class
  bin/main/seedu/address/model/tutee/Remark.class
  bin/main/seedu/address/model/tutee/Schedule.class
  bin/main/seedu/address/model/tutee/Subject.class
  bin/main/seedu/address/model/tutee/Tutee.class
  bin/main/seedu/address/model/tutee/UniquePersonList.class
  bin/main/seedu/address/model/tutee/exceptions/DuplicatePersonException.class
  bin/main/seedu/address/model/tutee/exceptions/PersonNotFoundException.class
  bin/test/seedu/address/logic/commands/EditTuteeDescriptorTest.class
  bin/test/seedu/address/logic/commands/RemarkCommandTest.class
  bin/test/seedu/address/logic/parser/TuteeManagingSystemParserTest.class
  bin/test/seedu/address/model/TuteeManagingSystemTest$TuteeManagingSystemStub.class
  bin/test/seedu/address/model/TuteeManagingSystemTest.class
  bin/test/seedu/address/model/tutee/AddressTest.class
  bin/test/seedu/address/model/tutee/EmailTest.class
  bin/test/seedu/address/model/tutee/NameContainsKeywordsPredicateTest.class
  bin/test/seedu/address/model/tutee/NameTest.class
  bin/test/seedu/address/model/tutee/PhoneTest.class
  bin/test/seedu/address/model/tutee/TuteeTest.class
  bin/test/seedu/address/model/tutee/UniqueTuteeListTest.class
  bin/test/seedu/address/storage/JsonAdaptedTuteeTest.class
  bin/test/seedu/address/storage/JsonSerializableTuteeManagingSystemTest.class
  bin/test/seedu/address/storage/JsonTuteeManagingSystemStorageTest.class
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/data/JsonSerializableTuteeManagingSystemTest/duplicatePersonTuteeManagingSystem.json
  src/test/data/JsonSerializableTuteeManagingSystemTest/invalidPersonTuteeManagingSystem.json
  src/test/data/JsonSerializableTuteeManagingSystemTest/typicalPersonsTuteeManagingSystem.json
  src/test/data/JsonTuteeManagingSystemStorageTest/invalidAndValidPersonTuteeManagingSystem.json
  src/test/data/JsonTuteeManagingSystemStorageTest/invalidPersonTuteeManagingSystem.json
  src/test/data/JsonTuteeManagingSystemStorageTest/notJsonFormatTuteeManagingSystem.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTuteeTest.java
  src/test/java/seedu/address/storage/JsonSerializableTuteeManagingSystemTest.java
  src/test/java/seedu/address/storage/JsonTuteeManagingSystemStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Chore

#53 Fixed Compiling error
  src/main/java/seedu/address/model/tutee/fields/Subject.java
Labels: priority.High, type.Bug, severity.High

#54 branch filter bugs
  src/main/java/seedu/address/model/tutee/fields/Email.java
  src/main/java/seedu/address/model/tutee/fields/EndTime.java
  src/main/java/seedu/address/model/tutee/fields/Name.java
  src/main/java/seedu/address/model/tutee/fields/Phone.java
  src/main/java/seedu/address/model/tutee/fields/Schedule.java
  src/main/java/seedu/address/model/tutee/fields/StartTime.java
  src/main/java/seedu/address/model/tutee/fields/Subject.java
Labels: type.Bug

#58 Add filterCommandTest and some refactoring
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/tutee/fields/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/model/TuteeManagingSystemTest.java
  src/test/java/seedu/address/storage/JsonSerializableTuteeManagingSystemTest.java
  src/test/java/seedu/address/storage/JsonTuteeManagingSystemStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#61 Update dg by including implementation for Filter feature
  docs/DeveloperGuide.md
Labels: priority.High

#64 Add DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Enhancement

#71 Update ug
  docs/UserGuide.md
  docs/images/learnExample.PNG
  docs/images/unlearnExample.PNG
Labels: priority.Medium, type.Enhancement

#73 Fix message error bug wrong information
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/logic/commands/UnlearnCommand.java
Labels: priority.Medium, severity.Medium
